// Generated by scripts/sync-protocol.mjs from the 2dai-server repo. Do not edit here.
import { z } from 'zod'

export const AUTH_MESSAGE_PREFIX = '2dai-auth-v1'

export interface AuthMessageParts {
  nonce: string
  deviceId: string
  workspaceId: string
  serverOrigin: string
}

// Both sides build the exact bytes to sign, so the server never asks a device to
// sign something it did not construct itself.
export function authMessage({ nonce, deviceId, workspaceId, serverOrigin }: AuthMessageParts): string {
  return [AUTH_MESSAGE_PREFIX, nonce, deviceId, workspaceId, serverOrigin].join('\n')
}

export const ChallengeRequest = z.object({ deviceId: z.string().uuid() })
export const ChallengeResponse = z.object({ nonce: z.string(), expiresAt: z.string() })
export type ChallengeResponse = z.infer<typeof ChallengeResponse>

export const SessionRequest = z.object({
  deviceId: z.string().uuid(),
  nonce: z.string().min(16),
  signature: z.string().min(16),
})

export const Session = z.object({ token: z.string(), expiresAt: z.string() })
export type Session = z.infer<typeof Session>

export const CHALLENGE_TTL_SECONDS = 60
export const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60
export const SESSION_REFRESH_AFTER_SECONDS = 60 * 60
