// Generated by scripts/sync-protocol.mjs from the 2dai-server repo. Do not edit here.
import { z } from 'zod'

export const WorkspaceRole = z.enum(['admin', 'member'])
export type WorkspaceRole = z.infer<typeof WorkspaceRole>

export const WorkspaceSummary = z.object({
  id: z.string(),
  name: z.string(),
})
export type WorkspaceSummary = z.infer<typeof WorkspaceSummary>

export const UserSummary = z.object({
  id: z.string(),
  displayName: z.string(),
  memberTag: z.string(),
  role: WorkspaceRole,
  createdAt: z.string(),
})
export type UserSummary = z.infer<typeof UserSummary>

export const DeviceSummary = z.object({
  id: z.string(),
  name: z.string(),
  createdAt: z.string(),
  lastSeenAt: z.string().nullable(),
  revokedAt: z.string().nullable(),
})
export type DeviceSummary = z.infer<typeof DeviceSummary>

export const Me = z.object({
  workspace: WorkspaceSummary,
  user: UserSummary,
  device: DeviceSummary,
  devices: z.array(DeviceSummary),
})
export type Me = z.infer<typeof Me>

export const DISPLAY_NAME_MAX = 60
export const DEVICE_NAME_MAX = 60

export const DisplayName = z.string().trim().min(1).max(DISPLAY_NAME_MAX)
export const DeviceName = z.string().trim().min(1).max(DEVICE_NAME_MAX)

export const UpdateMeRequest = z.object({ displayName: DisplayName })
export const UpdateDeviceRequest = z.object({ name: DeviceName })
