// Generated by scripts/sync-protocol.mjs from the 2dai-server repo. Do not edit here.
import { z } from 'zod'

// Bump only on breaking wire changes. The client checks this at connect time.
export const PROTOCOL_VERSION = 1

export const ServerInfo = z.object({
  name: z.string(),
  mode: z.enum(['single', 'multi']),
  version: z.string(),
  protocolVersion: z.number().int(),
  instanceId: z.string(),
  publicUrl: z.string(),
  features: z.object({
    catalog: z.boolean(),
    websocket: z.boolean(),
  }),
})
export type ServerInfo = z.infer<typeof ServerInfo>

export * from './identity.js'
export * from './auth.js'
export * from './invites.js'
