// Generated by scripts/sync-protocol.mjs from the 2dai-server repo. Do not edit here.
import { z } from 'zod'
import { DeviceName, DisplayName, DeviceSummary, UserSummary, WorkspaceSummary } from './identity.js'
import { Session } from './auth.js'

// An invite carries a set of grants. Exactly one grant decides who the redeemer
// becomes; later chunks add grants such as join-list that ride alongside.
export const InviteGrant = z.discriminatedUnion('type', [
  z.object({ type: z.literal('claim-server') }),
  z.object({ type: z.literal('join-workspace') }),
  z.object({ type: z.literal('link-device'), userId: z.string().uuid(), revokeOtherDevices: z.boolean().default(false) }),
])
export type InviteGrant = z.infer<typeof InviteGrant>

export const InviteKind = z.enum(['claim-server', 'join-workspace', 'link-device'])
export type InviteKind = z.infer<typeof InviteKind>

export const SixDigitCode = z.string().regex(/^\d{6}$/)

export const INVITE_DEFAULT_TTL_SECONDS = 15 * 60
export const INVITE_MAX_TTL_SECONDS = 7 * 24 * 60 * 60
export const CLAIM_INVITE_TTL_SECONDS = 24 * 60 * 60

export const CreateInviteRequest = z.object({
  grants: z.array(InviteGrant).min(1),
  expiresInSeconds: z.number().int().min(60).max(INVITE_MAX_TTL_SECONDS).default(INVITE_DEFAULT_TTL_SECONDS),
  withCode: z.boolean().default(true),
})
export type CreateInviteRequest = z.infer<typeof CreateInviteRequest>

export const InviteCreated = z.object({
  id: z.string(),
  kind: InviteKind,
  secret: z.string(),
  code: z.string().nullable(),
  url: z.string(),
  expiresAt: z.string(),
})
export type InviteCreated = z.infer<typeof InviteCreated>

export const InviteSummary = z.object({
  id: z.string(),
  kind: InviteKind,
  code: z.string().nullable(),
  expiresAt: z.string(),
  createdAt: z.string(),
  createdVia: z.enum(['bootstrap', 'admin', 'user']),
  targetUserId: z.string().nullable(),
})
export type InviteSummary = z.infer<typeof InviteSummary>

const inviteReference = {
  secret: z.string().min(16).optional(),
  code: SixDigitCode.optional(),
}

// What a client shows before committing: "Join Marcus's Home Server?"
export const InviteLookupRequest = z.object(inviteReference).refine((value) => Boolean(value.secret) !== Boolean(value.code), {
  message: 'Provide exactly one of secret or code',
})
export const InviteLookup = z.object({
  kind: InviteKind,
  serverName: z.string(),
  workspaceName: z.string(),
  expiresAt: z.string(),
  displayNameRequired: z.boolean(),
  linkTo: z.object({ displayName: z.string(), memberTag: z.string() }).nullable(),
})
export type InviteLookup = z.infer<typeof InviteLookup>

export const RedeemRequest = z.object({
  ...inviteReference,
  displayName: DisplayName.optional(),
  deviceName: DeviceName,
  devicePublicKey: z.string().regex(/^[A-Za-z0-9_-]{43}$/, 'base64url of 32 raw Ed25519 bytes'),
}).refine((value) => Boolean(value.secret) !== Boolean(value.code), {
  message: 'Provide exactly one of secret or code',
})
export type RedeemRequest = z.infer<typeof RedeemRequest>

export const RedeemResponse = z.object({
  workspace: WorkspaceSummary,
  user: UserSummary,
  device: DeviceSummary,
  session: Session,
})
export type RedeemResponse = z.infer<typeof RedeemResponse>

// The link inside a QR code opens the app, which then talks to the server.
export function connectLink(appUrl: string, serverUrl: string, secret: string): string {
  const params = new URLSearchParams({ server: serverUrl, invite: secret })
  return `${appUrl.replace(/\/+$/, '')}/#/connect?${params.toString()}`
}
