// Generated by scripts/sync-protocol.mjs from the 2dai-server repo. Do not edit here.
import { z } from 'zod'

// ---- entities ------------------------------------------------------------------
// Field schemas mirror src/domain.ts in the client. `id` lives outside `data`
// (it is the op's entityId). `create` sends the full object; `set` sends a partial
// where null clears an optional field. listId and createdAt never change after
// creation: a task moving between lists is a delete plus a create.

export const EntityKind = z.enum(['list', 'section', 'project', 'task', 'event'])
export type EntityKind = z.infer<typeof EntityKind>

export const OpKind = z.enum(['create', 'set', 'delete'])
export type OpKind = z.infer<typeof OpKind>

export const EntityId = z.string().regex(/^[A-Za-z0-9_-]{1,64}$/)
const Position = z.string().min(1).max(64)
const Iso = z.string().min(10).max(40)
const DateKey = z.string().regex(/^\d{4}-\d{2}-\d{2}$/)
const TimeOfDay = z.string().regex(/^\d{2}:\d{2}$/)
const PreferredTimeSource = z.enum(['explicit', 'observed'])

export const ListData = z.object({
  name: z.string().min(1).max(200),
  color: z.string().max(32),
  position: Position,
}).strict()

export const SectionData = z.object({
  listId: EntityId,
  projectId: EntityId.optional(),
  name: z.string().max(200),
  position: Position,
}).strict()

export const ProjectData = z.object({
  listId: EntityId,
  name: z.string().max(200),
  position: Position,
  includeInPlanner: z.boolean().optional(),
  archived: z.boolean(),
}).strict()

export const TaskData = z.object({
  listId: EntityId,
  sectionId: EntityId.optional(),
  projectId: EntityId.optional(),
  title: z.string().max(300),
  notes: z.string().max(10_000).optional(),
  position: Position,
  effort: z.number().min(0).max(10_000),
  intervalDays: z.number().int().min(0).max(36_500).optional(),
  fixedInterval: z.boolean(),
  dueFilters: z.string().max(200).optional(),
  preferredTime: TimeOfDay.optional(),
  preferredTimeSource: PreferredTimeSource.optional(),
  weekdayPreferredTime: TimeOfDay.optional(),
  weekdayPreferredTimeSource: PreferredTimeSource.optional(),
  weekendPreferredTime: TimeOfDay.optional(),
  weekendPreferredTimeSource: PreferredTimeSource.optional(),
  lastCompletedAt: Iso.optional(),
  trackedMs: z.number().min(0).optional(),
  nextDueAt: DateKey,
  scheduledForPlanner: z.boolean().optional(),
  archived: z.boolean(),
  createdAt: Iso,
  updatedAt: Iso,
  movedFrom: EntityId.optional(),
}).strict()

export const EventData = z.object({
  taskId: EntityId,
  action: z.enum(['completed', 'delayed', 'skipped']),
  effectiveDate: DateKey,
  createdAt: Iso,
  previousNextDueAt: DateKey.optional(),
  previousLastCompletedAt: Iso.optional(),
  previousArchived: z.boolean().optional(),
  previousPreferredTime: TimeOfDay.optional(),
  previousPreferredTimeSource: PreferredTimeSource.optional(),
  hasPreferredTimeSnapshot: z.boolean().optional(),
  previousWeekdayPreferredTime: TimeOfDay.optional(),
  previousWeekdayPreferredTimeSource: PreferredTimeSource.optional(),
  previousWeekendPreferredTime: TimeOfDay.optional(),
  previousWeekendPreferredTimeSource: PreferredTimeSource.optional(),
  hasDayTypeTimeSnapshot: z.boolean().optional(),
  previousEffort: z.number().optional(),
  previousTrackedMs: z.number().optional(),
}).strict()

export const CREATE_SCHEMAS: Record<EntityKind, z.ZodObject<z.ZodRawShape>> = {
  list: ListData,
  section: SectionData,
  project: ProjectData,
  task: TaskData,
  event: EventData,
}

const IMMUTABLE_FIELDS = new Set(['listId', 'createdAt'])

function setSchema(create: z.ZodObject<z.ZodRawShape>): z.ZodTypeAny {
  const shape: Record<string, z.ZodTypeAny> = {}
  for (const [field, schema] of Object.entries(create.shape as Record<string, z.ZodTypeAny>)) {
    if (IMMUTABLE_FIELDS.has(field)) continue
    // Optional fields may be cleared with null; required ones may only be replaced.
    const optional = schema.safeParse(undefined).success
    shape[field] = optional ? schema.nullable().optional() : schema.optional()
  }
  return z.object(shape).strict().refine((value) => Object.keys(value).length > 0, { message: 'set needs at least one field' })
}

export const SET_SCHEMAS: Record<EntityKind, z.ZodTypeAny> = {
  list: setSchema(ListData),
  section: setSchema(SectionData),
  project: setSchema(ProjectData),
  task: setSchema(TaskData),
  event: z.never(), // events are immutable: create and delete only
}

// ---- operations ---------------------------------------------------------------

export const HLC_PATTERN = /^\d{15}-[0-9a-f]{4}-[A-Za-z0-9-]{1,64}$/

export const ClientOp = z.object({
  opId: z.string().uuid(),
  listId: EntityId,
  entity: EntityKind,
  entityId: EntityId,
  kind: OpKind,
  data: z.record(z.string(), z.unknown()).optional(),
  hlc: z.string().regex(HLC_PATTERN),
})
export type ClientOp = z.infer<typeof ClientOp>

// Validates `data` against the entity's create or set schema.
export function validateOpData(op: ClientOp): { ok: true; data: Record<string, unknown> | undefined } | { ok: false; message: string } {
  if (op.kind === 'delete') return { ok: true, data: undefined }
  if (op.entity === 'list' && op.entityId !== op.listId) return { ok: false, message: 'a list entity id must equal its listId' }
  const schema = op.kind === 'create' ? CREATE_SCHEMAS[op.entity] : SET_SCHEMAS[op.entity]
  const result = schema.safeParse(op.data ?? {})
  if (!result.success) return { ok: false, message: result.error.issues.map((issue) => `${issue.path.join('.') || 'data'}: ${issue.message}`).join('; ') }
  const data = result.data as Record<string, unknown>
  if (op.kind === 'create' && op.entity !== 'list' && op.entity !== 'event' && data.listId !== op.listId) return { ok: false, message: 'data.listId must equal the op listId' }
  return { ok: true, data }
}

export const ServerOp = ClientOp.extend({
  seq: z.number().int(),
  userId: z.string(),
  deviceId: z.string(),
  receivedAt: z.string(),
})
export type ServerOp = z.infer<typeof ServerOp>

export const RejectionReason = z.enum(['invalid', 'clock_skew', 'not_member', 'role_insufficient', 'list_deleted', 'unknown_entity', 'over_limit'])
export type RejectionReason = z.infer<typeof RejectionReason>

export const PUSH_MAX_OPS = 500
export const PULL_DEFAULT_LIMIT = 500
export const PULL_MAX_LIMIT = 2000
// How far ahead of server time an op's clock may be before it is refused.
export const MAX_CLOCK_SKEW_MS = 10 * 60 * 1000

export const PushRequest = z.object({ ops: z.array(ClientOp).min(1).max(PUSH_MAX_OPS) })
export const PushResponse = z.object({
  serverTime: z.string(),
  accepted: z.array(z.object({ opId: z.string(), seq: z.number().int() })),
  rejected: z.array(z.object({ opId: z.string(), reason: RejectionReason, message: z.string().optional() })),
})
export type PushResponse = z.infer<typeof PushResponse>

export const ListRole = z.enum(['owner', 'manager', 'editor', 'viewer'])
export type ListRole = z.infer<typeof ListRole>

export const MembershipSummary = z.object({
  listId: z.string(),
  role: ListRole,
  ownerUserId: z.string(),
  visibility: z.enum(['private', 'public']),
  revokePolicy: z.enum(['keep', 'remove']),
  deleted: z.boolean(),
})
export type MembershipSummary = z.infer<typeof MembershipSummary>

export const PullRequest = z.object({
  cursors: z.record(EntityId, z.number().int().min(0)),
  limit: z.number().int().min(1).max(PULL_MAX_LIMIT).default(PULL_DEFAULT_LIMIT),
})
export type PullRequest = z.infer<typeof PullRequest>

export const PullListResult = z.object({
  ops: z.array(ServerOp),
  cursor: z.number().int(),
  more: z.boolean(),
  expired: z.boolean(),
})
export const PullResponse = z.object({
  serverTime: z.string(),
  lists: z.record(z.string(), PullListResult),
  memberships: z.array(MembershipSummary),
  revoked: z.array(z.string()),
})
export type PullResponse = z.infer<typeof PullResponse>

export const SnapshotEntity = z.object({
  entity: EntityKind,
  id: EntityId,
  data: z.record(z.string(), z.unknown()),
  clocks: z.record(z.string(), z.string()),
  createdHlc: z.string().nullable(),
  deletedHlc: z.string().nullable(),
})
export type SnapshotEntity = z.infer<typeof SnapshotEntity>

export const Snapshot = z.object({
  listId: z.string(),
  cursor: z.number().int(),
  membership: MembershipSummary,
  entities: z.array(SnapshotEntity),
})
export type Snapshot = z.infer<typeof Snapshot>
